// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/mydb.proto

package protov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MyDBService_ExecuteSQL_FullMethodName  = "/mydb.v1.MyDBService/ExecuteSQL"
	MyDBService_GetMetadata_FullMethodName = "/mydb.v1.MyDBService/GetMetadata"
)

// MyDBServiceClient is the client API for MyDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MyDBService provides SQL execution and metadata operations
type MyDBServiceClient interface {
	// ExecuteSQL executes a SQL statement and returns results
	ExecuteSQL(ctx context.Context, in *ExecuteSQLRequest, opts ...grpc.CallOption) (*ExecuteSQLResponse, error)
	// GetMetadata retrieves database schema information
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
}

type myDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyDBServiceClient(cc grpc.ClientConnInterface) MyDBServiceClient {
	return &myDBServiceClient{cc}
}

func (c *myDBServiceClient) ExecuteSQL(ctx context.Context, in *ExecuteSQLRequest, opts ...grpc.CallOption) (*ExecuteSQLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteSQLResponse)
	err := c.cc.Invoke(ctx, MyDBService_ExecuteSQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myDBServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, MyDBService_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyDBServiceServer is the server API for MyDBService service.
// All implementations must embed UnimplementedMyDBServiceServer
// for forward compatibility.
//
// MyDBService provides SQL execution and metadata operations
type MyDBServiceServer interface {
	// ExecuteSQL executes a SQL statement and returns results
	ExecuteSQL(context.Context, *ExecuteSQLRequest) (*ExecuteSQLResponse, error)
	// GetMetadata retrieves database schema information
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	mustEmbedUnimplementedMyDBServiceServer()
}

// UnimplementedMyDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMyDBServiceServer struct{}

func (UnimplementedMyDBServiceServer) ExecuteSQL(context.Context, *ExecuteSQLRequest) (*ExecuteSQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteSQL not implemented")
}
func (UnimplementedMyDBServiceServer) GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedMyDBServiceServer) mustEmbedUnimplementedMyDBServiceServer() {}
func (UnimplementedMyDBServiceServer) testEmbeddedByValue()                     {}

// UnsafeMyDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyDBServiceServer will
// result in compilation errors.
type UnsafeMyDBServiceServer interface {
	mustEmbedUnimplementedMyDBServiceServer()
}

func RegisterMyDBServiceServer(s grpc.ServiceRegistrar, srv MyDBServiceServer) {
	// If the following call pancis, it indicates UnimplementedMyDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MyDBService_ServiceDesc, srv)
}

func _MyDBService_ExecuteSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyDBServiceServer).ExecuteSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyDBService_ExecuteSQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyDBServiceServer).ExecuteSQL(ctx, req.(*ExecuteSQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyDBService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyDBServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyDBService_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyDBServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MyDBService_ServiceDesc is the grpc.ServiceDesc for MyDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mydb.v1.MyDBService",
	HandlerType: (*MyDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteSQL",
			Handler:    _MyDBService_ExecuteSQL_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _MyDBService_GetMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/mydb.proto",
}
