// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/mydb.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteSQLRequest contains a SQL statement to execute
type ExecuteSQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // For transaction context (future use)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSQLRequest) Reset() {
	*x = ExecuteSQLRequest{}
	mi := &file_api_proto_mydb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSQLRequest) ProtoMessage() {}

func (x *ExecuteSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSQLRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSQLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteSQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteSQLRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ExecuteSQLResponse contains the result of SQL execution
type ExecuteSQLResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExecuteSQLResponse_QueryResult
	//	*ExecuteSQLResponse_CommandResult
	//	*ExecuteSQLResponse_Error
	Result        isExecuteSQLResponse_Result `protobuf_oneof:"result"`
	SessionId     string                      `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session ID for context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSQLResponse) Reset() {
	*x = ExecuteSQLResponse{}
	mi := &file_api_proto_mydb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSQLResponse) ProtoMessage() {}

func (x *ExecuteSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSQLResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSQLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteSQLResponse) GetResult() isExecuteSQLResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteSQLResponse) GetQueryResult() *QueryResult {
	if x != nil {
		if x, ok := x.Result.(*ExecuteSQLResponse_QueryResult); ok {
			return x.QueryResult
		}
	}
	return nil
}

func (x *ExecuteSQLResponse) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Result.(*ExecuteSQLResponse_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *ExecuteSQLResponse) GetError() *ErrorResult {
	if x != nil {
		if x, ok := x.Result.(*ExecuteSQLResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ExecuteSQLResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type isExecuteSQLResponse_Result interface {
	isExecuteSQLResponse_Result()
}

type ExecuteSQLResponse_QueryResult struct {
	QueryResult *QueryResult `protobuf:"bytes,1,opt,name=query_result,json=queryResult,proto3,oneof"` // For SELECT queries
}

type ExecuteSQLResponse_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,2,opt,name=command_result,json=commandResult,proto3,oneof"` // For DDL/DML commands
}

type ExecuteSQLResponse_Error struct {
	Error *ErrorResult `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // For errors
}

func (*ExecuteSQLResponse_QueryResult) isExecuteSQLResponse_Result() {}

func (*ExecuteSQLResponse_CommandResult) isExecuteSQLResponse_Result() {}

func (*ExecuteSQLResponse_Error) isExecuteSQLResponse_Result() {}

// QueryResult contains rows returned by a SELECT query
type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_api_proto_mydb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResult) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryResult) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Row represents a single row of query results
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"` // Encoded column values
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_api_proto_mydb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// CommandResult indicates success of a DDL/DML command
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                // Human-readable message (e.g., "1 row inserted")
	RowsAffected  int64                  `protobuf:"varint,2,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"` // Number of rows affected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_api_proto_mydb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{4}
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResult) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

// ErrorResult contains error information
type ErrorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Error message
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`       // Error code (e.g., "PARSE_ERROR", "CONSTRAINT_VIOLATION")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResult) Reset() {
	*x = ErrorResult{}
	mi := &file_api_proto_mydb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResult) ProtoMessage() {}

func (x *ErrorResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResult.ProtoReflect.Descriptor instead.
func (*ErrorResult) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// GetMetadataRequest requests schema information
type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // Schema name (empty for all schemas)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_api_proto_mydb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{6}
}

func (x *GetMetadataRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

// GetMetadataResponse contains schema metadata
type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*TableInfo           `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_api_proto_mydb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetadataResponse) GetTables() []*TableInfo {
	if x != nil {
		return x.Tables
	}
	return nil
}

// TableInfo describes a database table
type TableInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []*ColumnInfo          `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	Indexes       []*IndexInfo           `protobuf:"bytes,4,rep,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableInfo) Reset() {
	*x = TableInfo{}
	mi := &file_api_proto_mydb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableInfo) ProtoMessage() {}

func (x *TableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableInfo.ProtoReflect.Descriptor instead.
func (*TableInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{8}
}

func (x *TableInfo) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *TableInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableInfo) GetColumns() []*ColumnInfo {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *TableInfo) GetIndexes() []*IndexInfo {
	if x != nil {
		return x.Indexes
	}
	return nil
}

// ColumnInfo describes a table column
type ColumnInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	PrimaryKey    bool                   `protobuf:"varint,4,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnInfo) Reset() {
	*x = ColumnInfo{}
	mi := &file_api_proto_mydb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnInfo) ProtoMessage() {}

func (x *ColumnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnInfo.ProtoReflect.Descriptor instead.
func (*ColumnInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{9}
}

func (x *ColumnInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ColumnInfo) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *ColumnInfo) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

// IndexInfo describes a table index
type IndexInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Unique        bool                   `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexInfo) Reset() {
	*x = IndexInfo{}
	mi := &file_api_proto_mydb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexInfo) ProtoMessage() {}

func (x *IndexInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mydb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexInfo.ProtoReflect.Descriptor instead.
func (*IndexInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_mydb_proto_rawDescGZIP(), []int{10}
}

func (x *IndexInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexInfo) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *IndexInfo) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

var File_api_proto_mydb_proto protoreflect.FileDescriptor

const file_api_proto_mydb_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/mydb.proto\x12\amydb.v1\"D\n" +
	"\x11ExecuteSQLRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xe7\x01\n" +
	"\x12ExecuteSQLResponse\x129\n" +
	"\fquery_result\x18\x01 \x01(\v2\x14.mydb.v1.QueryResultH\x00R\vqueryResult\x12?\n" +
	"\x0ecommand_result\x18\x02 \x01(\v2\x16.mydb.v1.CommandResultH\x00R\rcommandResult\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x14.mydb.v1.ErrorResultH\x00R\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionIdB\b\n" +
	"\x06result\"I\n" +
	"\vQueryResult\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12 \n" +
	"\x04rows\x18\x02 \x03(\v2\f.mydb.v1.RowR\x04rows\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"N\n" +
	"\rCommandResult\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rrows_affected\x18\x02 \x01(\x03R\frowsAffected\";\n" +
	"\vErrorResult\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\",\n" +
	"\x12GetMetadataRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\"A\n" +
	"\x13GetMetadataResponse\x12*\n" +
	"\x06tables\x18\x01 \x03(\v2\x12.mydb.v1.TableInfoR\x06tables\"\x94\x01\n" +
	"\tTableInfo\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\acolumns\x18\x03 \x03(\v2\x13.mydb.v1.ColumnInfoR\acolumns\x12,\n" +
	"\aindexes\x18\x04 \x03(\v2\x12.mydb.v1.IndexInfoR\aindexes\"q\n" +
	"\n" +
	"ColumnInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x1f\n" +
	"\vprimary_key\x18\x04 \x01(\bR\n" +
	"primaryKey\"Q\n" +
	"\tIndexInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x16\n" +
	"\x06unique\x18\x03 \x01(\bR\x06unique2\x9e\x01\n" +
	"\vMyDBService\x12E\n" +
	"\n" +
	"ExecuteSQL\x12\x1a.mydb.v1.ExecuteSQLRequest\x1a\x1b.mydb.v1.ExecuteSQLResponse\x12H\n" +
	"\vGetMetadata\x12\x1b.mydb.v1.GetMetadataRequest\x1a\x1c.mydb.v1.GetMetadataResponseB2Z0github.com/hainn191297/myDb/api/proto/v1;protov1b\x06proto3"

var (
	file_api_proto_mydb_proto_rawDescOnce sync.Once
	file_api_proto_mydb_proto_rawDescData []byte
)

func file_api_proto_mydb_proto_rawDescGZIP() []byte {
	file_api_proto_mydb_proto_rawDescOnce.Do(func() {
		file_api_proto_mydb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_mydb_proto_rawDesc), len(file_api_proto_mydb_proto_rawDesc)))
	})
	return file_api_proto_mydb_proto_rawDescData
}

var file_api_proto_mydb_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_mydb_proto_goTypes = []any{
	(*ExecuteSQLRequest)(nil),   // 0: mydb.v1.ExecuteSQLRequest
	(*ExecuteSQLResponse)(nil),  // 1: mydb.v1.ExecuteSQLResponse
	(*QueryResult)(nil),         // 2: mydb.v1.QueryResult
	(*Row)(nil),                 // 3: mydb.v1.Row
	(*CommandResult)(nil),       // 4: mydb.v1.CommandResult
	(*ErrorResult)(nil),         // 5: mydb.v1.ErrorResult
	(*GetMetadataRequest)(nil),  // 6: mydb.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil), // 7: mydb.v1.GetMetadataResponse
	(*TableInfo)(nil),           // 8: mydb.v1.TableInfo
	(*ColumnInfo)(nil),          // 9: mydb.v1.ColumnInfo
	(*IndexInfo)(nil),           // 10: mydb.v1.IndexInfo
}
var file_api_proto_mydb_proto_depIdxs = []int32{
	2,  // 0: mydb.v1.ExecuteSQLResponse.query_result:type_name -> mydb.v1.QueryResult
	4,  // 1: mydb.v1.ExecuteSQLResponse.command_result:type_name -> mydb.v1.CommandResult
	5,  // 2: mydb.v1.ExecuteSQLResponse.error:type_name -> mydb.v1.ErrorResult
	3,  // 3: mydb.v1.QueryResult.rows:type_name -> mydb.v1.Row
	8,  // 4: mydb.v1.GetMetadataResponse.tables:type_name -> mydb.v1.TableInfo
	9,  // 5: mydb.v1.TableInfo.columns:type_name -> mydb.v1.ColumnInfo
	10, // 6: mydb.v1.TableInfo.indexes:type_name -> mydb.v1.IndexInfo
	0,  // 7: mydb.v1.MyDBService.ExecuteSQL:input_type -> mydb.v1.ExecuteSQLRequest
	6,  // 8: mydb.v1.MyDBService.GetMetadata:input_type -> mydb.v1.GetMetadataRequest
	1,  // 9: mydb.v1.MyDBService.ExecuteSQL:output_type -> mydb.v1.ExecuteSQLResponse
	7,  // 10: mydb.v1.MyDBService.GetMetadata:output_type -> mydb.v1.GetMetadataResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_mydb_proto_init() }
func file_api_proto_mydb_proto_init() {
	if File_api_proto_mydb_proto != nil {
		return
	}
	file_api_proto_mydb_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecuteSQLResponse_QueryResult)(nil),
		(*ExecuteSQLResponse_CommandResult)(nil),
		(*ExecuteSQLResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_mydb_proto_rawDesc), len(file_api_proto_mydb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_mydb_proto_goTypes,
		DependencyIndexes: file_api_proto_mydb_proto_depIdxs,
		MessageInfos:      file_api_proto_mydb_proto_msgTypes,
	}.Build()
	File_api_proto_mydb_proto = out.File
	file_api_proto_mydb_proto_goTypes = nil
	file_api_proto_mydb_proto_depIdxs = nil
}
